//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgeHeiwako.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArgeHeiwako.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein valider A-Satz hat eine Zeichenlänge von 128 Zeichen..
        /// </summary>
        internal static string EXP_MSG_VALID_A_SATZ_128_CHARACTERS {
            get {
                return ResourceManager.GetString("EXP_MSG_VALID_A_SATZ_128_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein valider A-Satz muss mit dem Zeichen &apos;A&apos; beginnen und enden..
        /// </summary>
        internal static string EXP_MSG_VALID_A_SATZ_MUST_START_END_WITH_A {
            get {
                return ResourceManager.GetString("EXP_MSG_VALID_A_SATZ_MUST_START_END_WITH_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine valide Kennung besteht aus 2 numerischen Zeichen..
        /// </summary>
        internal static string EXP_MSG_VALID_ABRECHNUNGSUNTERNEHMENKENNUNG {
            get {
                return ResourceManager.GetString("EXP_MSG_VALID_ABRECHNUNGSUNTERNEHMENKENNUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine valide ARGE-Version liegt im Wertebereich 03.00 und 99.99..
        /// </summary>
        internal static string EXP_MSG_VALID_ARGE_VERSION_RANGE {
            get {
                return ResourceManager.GetString("EXP_MSG_VALID_ARGE_VERSION_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine valide Kundennummer hat eine Zeichenlänge von 10 Zeichen..
        /// </summary>
        internal static string EXP_MSG_VALID_KUNDENNUMMER_LENGTH {
            get {
                return ResourceManager.GetString("EXP_MSG_VALID_KUNDENNUMMER_LENGTH", resourceCulture);
            }
        }
    }
}
